# Set prefix key.
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload tmux configuration file.
bind r source-file /home/chris/.tmux.conf \; display "Reloaded tmux.conf."

# Colors.
set -g default-terminal "tmux-256color"
set -as terminal-overrides 'rxvt*:RGB'
set -g status-style bg="#E85D5A",fg="white"
set-window-option -g window-status-style fg="white"

# Vim copy mode.
setw -g mode-keys vi
set -g status-keys vi

# Use vim pane traversal.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use vim start-selection and copy-selection.
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Configuration for neovim.
set-option -sg escape-time 10
set-option -g focus-events on
